# Generated by Django 4.2 on 2025-03-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='Product',
            new_name='product',
        ),
    ]
